
import type { Campaign } from './types';

export const campaignsData: Campaign[] = [
  {
    name: 'Campaña de Verano 2025',
    status: 'Activa',
    budget: 5000,
    spend: 3250.5,
    clicks: 1520,
    cpc: 2.14,
    ctr: 4.8,
    adCreative: {
      title: 'Sol y Arena',
      subtitle: 'La escapada perfecta de verano',
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'playa verano',
      cta: 'Reserva Ahora',
      discount: '15% OFF',
    },
  },
  {
    name: 'Ofertas de Vuelta al Cole',
    status: 'Pausada',
    budget: 3000,
    spend: 1230.0,
    clicks: 850,
    cpc: 1.45,
    ctr: 3.1,
    adCreative: {
      title: 'Vuelta al Cole',
      subtitle: 'Todo lo que necesitas para el nuevo año escolar',
      imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'escuela estudio',
      cta: 'Ver Ofertas',
    },
  },
  {
    name: 'Liquidación de Invierno',
    status: 'Finalizada',
    budget: 7500,
    spend: 7480.75,
    clicks: 4100,
    cpc: 1.82,
    ctr: 6.2,
  },
  {
    name: 'Lanzamiento Nueva Colección',
    status: 'Activa',
    budget: 10000,
    spend: 4500.0,
    clicks: 1800,
    cpc: 2.5,
    ctr: 5.5,
    adCreative: {
      title: 'Nueva Colección',
      subtitle: 'Estilo y elegancia para ti',
      imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'moda compras',
      cta: 'Descúbrela',
    },
  },
  {
    name: 'Promoción Fin de Semana',
    status: 'Borrador',
    budget: 1500,
    spend: 0.0,
    clicks: 0,
    cpc: 0.0,
    ctr: 0.0,
  },
   {
    name: 'Anuncio Premium',
    status: 'Activa',
    budget: 20000,
    spend: 15000,
    clicks: 5000,
    cpc: 3.00,
    ctr: 8.0,
    adCreative: {
      title: 'Streaming sin límites',
      subtitle: 'Disfruta de contenido 4K en todas tus plataformas favoritas',
      imageUrl: '', // No image for gradient card
      imageHint: 'streaming video',
      cta: 'Saber más',
    }
  },
  {
    name: 'Delivery Express',
    status: 'Activa',
    budget: 2500,
    spend: 1800,
    clicks: 1200,
    cpc: 1.5,
    ctr: 7.1,
     adCreative: {
      title: 'Delivery Express',
      subtitle: 'Comida a domicilio en 30 minutos',
      imageUrl: '',
      imageHint: 'comida delivery',
      cta: 'Pedir Ahora',
      discount: "15%",
    }
  },
   {
    name: 'Video Ad - SUV Eléctrico',
    status: 'Activa',
    budget: 30000,
    spend: 22000,
    clicks: 8000,
    cpc: 2.75,
    ctr: 9.2,
    adCreative: {
        title: "Nuevo SUV Eléctrico",
        subtitle: "Descubre el futuro",
        imageUrl: "https://images.unsplash.com/photo-1611652022417-a04094a14eda?q=80&w=1080&auto=format&fit=crop",
        imageHint: "carro electrico",
        cta: "Ver Video",
    }
  },
  {
    name: 'Restaurante La Plaza',
    status: 'Activa',
    budget: 4000,
    spend: 1500,
    clicks: 750,
    cpc: 2.0,
    ctr: 5.0,
    adCreative: {
      title: 'Restaurante La Plaza',
      subtitle: '¡Menú del día por solo 12€!',
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'restaurante interior',
      cta: 'Ver oferta',
      offerTitle: 'Menú del día completo por solo 12€ (precio normal 18€)',
      offerSubtitle: 'Válido hasta: 31 de Diciembre 2024',
      description: 'Disfruta de nuestro exquisito menú del día preparado con ingredientes frescos y locales. Incluye primer plato, segundo plato, postre y bebida.',
      location: 'Calle Mayor 15, Madrid',
      phone: '+34 91 123 4567',
      hours: 'Lunes a Domingo: 13:00 - 16:00 y 20:00 - 23:30',
    }
  },
  {
    name: 'Gimnasio FitLife',
    status: 'Activa',
    budget: 6000,
    spend: 2800,
    clicks: 1400,
    cpc: 2.0,
    ctr: 6.5,
    adCreative: {
      title: 'Gimnasio FitLife',
      subtitle: 'Primer mes gratis + entrenador personal',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'gimnasio fitness',
      cta: 'Ver oferta',
      offerTitle: '¡Transforma tu cuerpo y mente!',
      offerSubtitle: 'Únete a la comunidad FitLife hoy mismo.',
      description: 'Oferta exclusiva para nuevos miembros: obtén tu primer mes completamente gratis y una sesión de bienvenida con un entrenador personal para diseñar tu plan de entrenamiento perfecto. ¡Sin compromiso de permanencia!',
      services: [
        'Acceso ilimitado a todas las áreas del gimnasio',
        'Clases grupales incluidas (Yoga, Spinning, HIIT)',
        'Uso de la piscina y sauna',
        'Evaluación física inicial gratuita',
        'App móvil para seguimiento de progreso',
      ]
    }
  },
  {
    name: 'Tienda de Electrónicos',
    status: 'Activa',
    budget: 8000,
    spend: 5000,
    clicks: 2500,
    cpc: 2.0,
    ctr: 7.0,
    adCreative: {
      title: 'Tienda de Electrónicos',
      subtitle: 'Descuentos hasta 50% en smartphones',
      imageUrl: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?q=80&w=1080&auto=format&fit=crop',
      imageHint: 'tecnologia smartphones',
      cta: 'Más información',
      offerTitle: 'Descuentos de hasta 50% en smartphones seleccionados + financiación sin intereses',
      offerSubtitle: 'Válido hasta: 28 de Febrero 2025',
      description: 'Los mejores precios en tecnología. Smartphones, tablets, laptops y accesorios de las mejores marcas con garantía oficial.',
      location: 'Centro Comercial Plaza Norte, Local 234',
      phone: '+34 91 555 0123',
      hours: 'Lunes a Sábado: 10:00 - 22:00, Domingos: 12:00 - 20:00',
    }
  }
];
